# NumPy Opdrachten

In dit notebook vind je de volgende opdrachten:


- <a href="#np_opdracht1"> Opdracht 1</a> Maak deze opdracht ter voorbereiding op het college over NumPy.
- <a href="#np_opdracht2"> Opdracht 2</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht3"> Opdracht 3</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht4"> Opdracht 4</a> Deze opdracht is facultatief, voor als je meer uitdaging wilt.

<a id="np_opdracht1"></a>
## Opdracht 1 
**Maak deze opdracht ter voorbereiding op het college**

In [203]:
import numpy as np
import numpy

- Maak een 1D array x aan met de cijfers 0 t/m 5

In [204]:
x = np.arange(0,6)

- Laat de vorm (grootte van de dimensies) van de array zien

In [205]:
x.shape

(6,)

- Hervorm de array x tot een 2D array (2, 3) 

In [206]:
x = x.reshape(2,3)

- Wat is nu de vorm?


In [207]:
x.shape

(2, 3)

- Laat het datatype zien


In [208]:
type(x)

numpy.ndarray

- Sla een kopie van de array op in y


In [209]:
y = np.copy(x)

- Maak een transpose van x



In [210]:
x = np.transpose(x)

- Maak een transpose van y


In [211]:
y = np.transpose(y)

- Vermenigvuldig alle waarden van y met 2


In [212]:
y = y*2

- Concateneer de twee arrays in een nieuwe array `z`


In [213]:
z = np.concatenate((x,y))

- Geef het gemiddelde, modus, mediaan en de standaarddeviatie van z


In [214]:
from scipy.stats import mode
print(z)
print("average of z: ", np.average(z))
print("modus of z: ", mode(z))
print("median of z: ", np.median(z))
print("stdev of z: ", np.std(z))

[[ 0  3]
 [ 1  4]
 [ 2  5]
 [ 0  6]
 [ 2  8]
 [ 4 10]]
average of z:  3.75
modus of z:  ModeResult(mode=array([0, 3]), count=array([2, 1]))
median of z:  3.5
stdev of z:  2.9755951785595207


<a id="np_opdracht2"></a>
## Opdracht 2
**Python list vs. NumPy**

- Maak een list `lst` met 1.000.001 willekeurige getallen tussen 0 en 10 (gebruik `random.randint(0, 10)`)
- Bepaal de mediaan
- Maak een list met daarin het kwadraat van elk element in `lst`
- Maak een list met daarin alleen alle even getallen uit `lst`
- Maak een tweede list `lst2` met 1.000.001 willekeurige getallen
- Maak een list met daarin de som van de elementen uit `lst` en `lst2`, dus:
  - `lst_samen[0] = lst[0] + lst2[0]`,
  - `lst_samen[1] = lst[1] + lst2[1]`,
  - etc.

- Doe bovenstaande ook met Numpy

- Gebruik `%timeit` voor je code om de snelheid te vergelijken

In [1]:
import math
import random
import numpy as np
import statistics
import timeit

random.seed(0)

random_array = np.random.randint(0, 11, 1000_001)
random_array = random_array.tolist()
random_array2 = np.random.randint(0, 11, 1000_001)
random_array2 = random_array2.tolist()

random_array_square = []
random_array_even = []
random_array_together = []
def python_arrays():
    print(statistics.median(random_array))
    for i in range(len(random_array)): 
        random_array_square.append(random_array[i] ** 2)
        random_array_even.append(random_array[i]) if random_array[i] % 2 == 0 else None
        random_array_together.append(random_array[i] + random_array2[i])

random_array_numpy = np.random.randint(0, 11, 1000_001)
random_array_numpy2 = np.random.randint(0, 11, 1000_001)
def numpy_arrays():
    print(np.median(random_array_numpy))
    random_array_numpy_square = np.square(random_array_numpy)
    random_array_numpy_even = np.extract(random_array_numpy % 2 == 0, random_array_numpy)
    random_array_numpy_together = np.add(random_array_numpy, random_array_numpy2)

%timeit python_arrays()
print(timeit.timeit(python_arrays, number=10))
print(timeit.timeit(numpy_arrays, number=10))
    








5
5
5
5
5
5
5
5
236 ms ± 2.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5
5
5
5
5
5
5
5
5
5
2.3475137559998984
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
0.34870903299997735


<a id="np_opdracht3"></a>
## Opdracht 3

De blokcoördinator D.O. Cent van blok A  wil graag de cijfers analyseren en verwerken. Het blok bestaat uit 3 vakken, die door 10 studenten gevolgd zijn. Analyse omvat o.a. het bepalen van gemiddelde cijfer, het aantal voldoendes en cursusrendement. De verwerking bestaat uit het corrigeren van de cijfers.

In `blokAcijfers.txt` staan de cijfers per vak (naast elkaar staan de vakken, onder elkaar de studenten):

vak1 | vak2 | vak3
----|-------|------
6.5 | 7.3   | 6.4
8.0 | 8.0	| 8.5
3.2	| 4.0	| 5.0
7.9	| 7.1	| 3.5
7.3	| 7.8	| 8.0
8.6	| 8.0	| 9.0
4.0	| 6.0	| 5.5
7.3	| 7.8	| 7.8
4.5	| 5.6	| 7.7
5.0	| 7.0	| 7.2


In [216]:
import numpy as np

Start met de data verzamelen:
- Lees tekstbestand: blokAcijfers.txt in met `np.loadtxt`, sla de data op in een numpy array met naam `vCijfers`.
- Laat zien dat de gegevens goed ingelezen zijn.
- Toon de array attributen.

In [217]:
import numpy as np
vCijfers = np.loadtxt("blokAcijfers.txt")
print(vCijfers)
print(vCijfers.shape)

[[6.5 7.3 6.4]
 [8.  8.  8.5]
 [3.2 4.  5. ]
 [7.9 7.1 3.5]
 [7.3 7.8 8. ]
 [8.6 8.  9. ]
 [4.  6.  5.5]
 [7.3 7.8 7.8]
 [4.5 5.6 7.7]
 [5.  7.  7.2]]
(10, 3)


De docent ziet dat er 2 cijfers fout zijn en wil deze corrigeren
-	Wijzig de volgende cijfers:
    *	vak-2, student-3  cijfer 4.0 moet 4.3 worden.
    *	vak-1, student-10, cijfer 5.0 moet 4.8 worden.

In [218]:
vCijfers[2,1] = 4.3
vCijfers[9,0] = 4.8


De docent wil wat basisgegevens weten.
-	Bepaal minimum, maximum en gemiddelde van alle cijfers.
-	Bepaal minimum, maximum en gemiddelde van elk vak (3 getallen).
-	Bepaal minimum, maximum en gemiddelde van elke student (10 getallen).

In [219]:
print("minimum of vCijfers: ", np.min(vCijfers))
print("maximum of vCijfers: ", np.max(vCijfers))
print("average of vCijfers: ", np.average(vCijfers))

minimum of vCijfers:  3.2
maximum of vCijfers:  9.0
average of vCijfers:  6.653333333333333


In [220]:
vCijfers_class = np.transpose(vCijfers)
# print(vCijfers_class.sh)
for i in range(vCijfers_class.shape[0]):
    print("Minimum of class", i+1, ":", np.min(vCijfers_class[i]))
    print("Maximum of class", i+1, ":", np.max(vCijfers_class[i]))
    print("average of class", i+1, ":", np.average(vCijfers_class[i]))

Minimum of class 1 : 3.2
Maximum of class 1 : 8.6
average of class 1 : 6.209999999999999
Minimum of class 2 : 4.3
Maximum of class 2 : 8.0
average of class 2 : 6.890000000000001
Minimum of class 3 : 3.5
Maximum of class 3 : 9.0
average of class 3 : 6.860000000000001


In [221]:
for i in range(vCijfers.shape[0]):
    print("Minimum of student", i+1, ":", np.min(vCijfers[i]))
    print("Maximum of student", i+1, ":", np.max(vCijfers[i]))
    print("average of student", i+1, ":", np.average(vCijfers[i]))

Minimum of student 1 : 6.4
Maximum of student 1 : 7.3
average of student 1 : 6.733333333333334
Minimum of student 2 : 8.0
Maximum of student 2 : 8.5
average of student 2 : 8.166666666666666
Minimum of student 3 : 3.2
Maximum of student 3 : 5.0
average of student 3 : 4.166666666666667
Minimum of student 4 : 3.5
Maximum of student 4 : 7.9
average of student 4 : 6.166666666666667
Minimum of student 5 : 7.3
Maximum of student 5 : 8.0
average of student 5 : 7.7
Minimum of student 6 : 8.0
Maximum of student 6 : 9.0
average of student 6 : 8.533333333333333
Minimum of student 7 : 4.0
Maximum of student 7 : 6.0
average of student 7 : 5.166666666666667
Minimum of student 8 : 7.3
Maximum of student 8 : 7.8
average of student 8 : 7.633333333333333
Minimum of student 9 : 4.5
Maximum of student 9 : 7.7
average of student 9 : 5.933333333333334
Minimum of student 10 : 4.8
Maximum of student 10 : 7.2
average of student 10 : 6.333333333333333


De docent wil graag zien wat de cijfers zijn als ze afgerond worden op hele getallen.
-	Kopieer de array naar een nieuwe array.
-	Rond de waarden af.
-	Laat de resultaten zien.

In [222]:
vCijfers_copy = np.copy(vCijfers)
vCijfers_copy = np.rint(vCijfers_copy)
print(vCijfers_copy)

[[6. 7. 6.]
 [8. 8. 8.]
 [3. 4. 5.]
 [8. 7. 4.]
 [7. 8. 8.]
 [9. 8. 9.]
 [4. 6. 6.]
 [7. 8. 8.]
 [4. 6. 8.]
 [5. 7. 7.]]


Er is een fout gemaakt bij de cijfers van het 1e vak. Iedere student krijgt 0.5 punt extra erbij.
-	Vul een ‘ophoogarray’ bestaande uit 3 kolommen en elk 10 rijen en vul deze eerst met 0.0 en daarna de eerste rij met de waarden 0.5.
-	Tel de ophoogarray op bij de cijfer array.

In [223]:
ophoogarray = np.zeros((10,3))
ophoogarray[:, 0] = 0.5
vCijfers = vCijfers + ophoogarray

De docent wil een lijstje waarin hij in één opslag ziet waar een voldoende (`True`) en waar een onvoldoende (`False`) staat.  
-	Maakt dit lijstje.

In [225]:

print(vCijfers)
vCijfers_bool = np.where(vCijfers >= 5.5, True, False)
print(vCijfers_bool)

[[7.  7.3 6.4]
 [8.5 8.  8.5]
 [3.7 4.3 5. ]
 [8.4 7.1 3.5]
 [7.8 7.8 8. ]
 [9.1 8.  9. ]
 [4.5 6.  5.5]
 [7.8 7.8 7.8]
 [5.  5.6 7.7]
 [5.3 7.  7.2]]
[[ True  True  True]
 [ True  True  True]
 [False False False]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]]


<a id="np_opdracht4"></a>
## Opdracht 4
**Deze opdracht is facultatief**

In [ ]:
import numpy as np

#### 3. Create a null vector of size 10

#### 6.  Create a null vector of size 10 but the fifth value which is 1

#### 8.  Reverse a vector with values ranging from 10 to 49 (first element becomes last)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### 11. Create a 3x3 identity matrix

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

#### 15. Create a 2d array with 1 on the border and 0 inside

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

#### 29. How to round away from zero a float array ?

#### 30. How to find common values between two arrays?

#### 36. Extract the integer part of a random array using 5 different methods

In [ ]:
Z = np.random.uniform(0,10,10)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

#### 40. Create a random vector of size 10 and sort it

#### 42. Consider two random array A and B, check if they are equal

#### 45. Create random vector of size 10 and replace the maximum value by 0

#### 50. How to find the closest value (to a given scalar) in a vector?

In [ ]:
v = np.random.uniform(0,100)

#### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances

In [ ]:
Z = np.random.random((10,2))


#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 72. How to swap two rows of an array?

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 83. How to find the most frequent value in an array?

#### 89. How to get the n largest values of an array